# This is an example goreleaser.yaml file with some sane defaults.
project_name: avocatl/admiral
build:
  skip: true
changelog:
  sort: desc
  filters:
    exclude:
      - docs$
      - changelog$
      - Merge pull request